language: node_js

node_js:
  - "lts/*"

jobs:
  include:
    - before_install:
      - "cd project1"
    # install:
    #   - "npm install" as its the default should no longer be here
      script:
      - "gatsby build"
    - before_install:
      - "cd project2"
      script:
      - "gatsby build"

# OPTIONAL Install apt addons
# OPTIONAL Install cache components
# before_install
# install
# before_script
# script
# OPTIONAL before_cache (for cleaning up cache)
# after_success or after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script